---
- name: DRIVE-SETUP | Ensure lvm2 and xfs packages are installed
  apt:
    pkg:
     - lvm2
     - xfsprogs
    state: present
    update_cache: yes
    cache_valid_time: 3600  # only update apt cache if it's not been updated in over 1 hour (3,600 seconds)
  become: yes

# equivalent to: vgcreate vg.gluster /dev/sda
- name: DRIVE-SETUP | Ensure LVM Volume Group is created
  lvg:
    vg: vg.gluster
    pvs: /dev/sda
    force: no
  become: yes

# equivalent to: lvcreate --thinpool -l 70%VG lv.thin vg.gluster
- name: DRIVE-SETUP | Ensure LVM Logical Volume Thin Pool is created
  lvol:
    thinpool: lv.thin
    size: 70%VG
    vg: vg.gluster
    force: no
  become: yes

## !! WARNING !! Changing these settings could result in formatting the drive
- name: DRIVE-SETUP | Check if the LVM Thin Pool needs creating or editing
  filesystem: &xfs_format_params
    dev: /dev/mapper/vg.gluster-lv.thin
    fstype: xfs
    opts: -i size=512
  check_mode: yes
  register: xfs_format

- name: DRIVE-SETUP | Ensure the LVM Thin Pool is not mounted if the XFS filesystem needs creating or editing
  mount:
    path: /data/glusterfs/hms-gfs-volume/brick{{ ansible_hostname[-2:] }}
    src: /dev/mapper/vg.gluster-lv.thin
    state: unmounted
  become: yes
  when: xfs_format.changed

- name: DRIVE-SETUP | Ensure the LVM Thin Pool is formated XFS
  filesystem: *xfs_format_params
  become: yes

- name: DRIVE-SETUP | Ensure LVM Thin Pool is in fstab and mounted
  mount:
    path: /data/glusterfs/hms-gfs-volume/brick{{ ansible_hostname[-2:] }}
    src: /dev/mapper/vg.gluster-lv.thin
    fstype: xfs
    opts:
    state: mounted
  become: yes
