---
- name: SETUP | Ensure each host has the other hosts in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^\s*{{hostvars[item].ansible_default_ipv4.address}}\s*{{item}}\s*$'
    line: "{{hostvars[item].ansible_default_ipv4.address}}\t{{item}}"
  when: item != inventory_hostname
  loop: "{{ ansible_play_hosts_all }}"
  become: yes

- import_tasks: drive-setup.yml
  tags: drive-setup



#- name: GLUSTERFS | Ensure GlusterFS is installed
#  apt:
