---
- name: SETUP | Ensure each host has the other hosts in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^\s*{{hostvars[item].ansible_default_ipv4.address}}\s*{{item}}\s*$'
    line: "{{hostvars[item].ansible_default_ipv4.address}}\t{{item}}"
  when: item != inventory_hostname
  loop: "{{ ansible_play_hosts_all }}"
  become: yes

- import_tasks: drive-setup.yml
  tags: drive-setup

#- name: INSTALL | Ensure software-properties-common is installed so the repo
#    apt:
#      pkg:
#      - software-properties-common
#    state: present
#    update_cache: yes
#    cache_valid_time: 3600  # only update apt cache if it's not been updated in over 1 hour (3,600 seconds)
#  become: yes

- name: INSTALL | Ensure the GlusterFS repo is added to the sources list
  apt_repository:
    repo: ppa:gluster/glusterfs-7
    state: present
  become: yes

- name: INSTALL | Ensure glusterfs-server is installed
  apt:
    pkg:
    - glusterfs-server
    state: present
    update_cache: yes
    cache_valid_time: 3600  # only update apt cache if it's not been updated in over 1 hour (3,600 seconds)
  become: yes

- name: SERVICE | Ensure the GlusterFS service is enabled and running
  service:
    name: glusterd
    state: started
    enabled: yes
  become: yes
